[2024-05-19T19:38:14.941+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-19T19:38:15.000+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_book_dag.get_soup_operator manual__2024-05-19T19:38:09.612214+00:00 [queued]>
[2024-05-19T19:38:15.023+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_book_dag.get_soup_operator manual__2024-05-19T19:38:09.612214+00:00 [queued]>
[2024-05-19T19:38:15.025+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-05-19T19:38:15.066+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_soup_operator> on 2024-05-19 19:38:09.612214+00:00
[2024-05-19T19:38:15.082+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=371) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-19T19:38:15.086+0000] {standard_task_runner.py:63} INFO - Started process 373 to run task
[2024-05-19T19:38:15.091+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'get_book_dag', 'get_soup_operator', 'manual__2024-05-19T19:38:09.612214+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/get_book_dag.py', '--cfg-path', '/tmp/tmppzm8koa5']
[2024-05-19T19:38:15.096+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask get_soup_operator
[2024-05-19T19:38:15.233+0000] {task_command.py:426} INFO - Running <TaskInstance: get_book_dag.get_soup_operator manual__2024-05-19T19:38:09.612214+00:00 [running]> on host 60554ca90225
[2024-05-19T19:38:15.513+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='get_book_dag' AIRFLOW_CTX_TASK_ID='get_soup_operator' AIRFLOW_CTX_EXECUTION_DATE='2024-05-19T19:38:09.612214+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-19T19:38:09.612214+00:00'
[2024-05-19T19:38:15.517+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-19T19:38:16.083+0000] {warnings.py:110} WARNING - /opt/***/dags/get_book_dag.py:22: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 22 of the file /opt/***/dags/get_book_dag.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  soup = BeautifulSoup(response.text)

[2024-05-19T19:38:16.158+0000] {python.py:237} INFO - Done. Returned value was:                                                    0
0  html PUBLIC "-//W3C//DTD XHTML 1.0 Transitiona...
1  [[[Человек, который знал все - Сахновский Игор...
[2024-05-19T19:38:16.243+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-19T19:38:16.290+0000] {xcom.py:675} ERROR - Object of type DataFrame is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-05-19T19:38:16.298+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serde.py", line 148, in serialize
    data, serialized_classname, version, is_serialized = _serializers[qn].serialize(o)
                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/serialization/serializers/pandas.py", line 49, in serialize
    table = pa.Table.from_pandas(o)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/table.pxi", line 4525, in pyarrow.lib.Table.from_pandas
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/pandas_compat.py", line 611, in dataframe_to_arrays
    arrays = [convert_column(c, f)
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/pandas_compat.py", line 598, in convert_column
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/pyarrow/pandas_compat.py", line 592, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/array.pxi", line 345, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 85, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ("Expected bytes, got a 'Tag' object", 'Conversion failed for column 0 with type object')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 486, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3197, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 246, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 673, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2024-05-19T19:38:16.329+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=get_book_dag, task_id=get_soup_operator, run_id=manual__2024-05-19T19:38:09.612214+00:00, execution_date=20240519T193809, start_date=20240519T193815, end_date=20240519T193816
[2024-05-19T19:38:16.362+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 18 for task get_soup_operator (Object of type DataFrame is not JSON serializable; 373)
[2024-05-19T19:38:16.390+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-19T19:38:16.450+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-19T19:38:16.455+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
